# Generated by Django 4.1.2 on 2025-02-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Этап', 'verbose_name_plural': 'Этапы'},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'verbose_name': 'Подзадача', 'verbose_name_plural': 'Подзадачи'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='taskfile',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='taskphoto',
            options={'verbose_name': 'Фотографии', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'verbose_name': 'Тип задачи', 'verbose_name_plural': 'Типы задач'},
        ),
        migrations.AlterModelOptions(
            name='userposition',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
    ]
